### PR TITLE
Add support for Windows

### PR DESCRIPTION
**Pull request by fritzmg**
This PR adds support for Windows by using `tasklist /FI "PID eq …"`. Since this executable will always exit with code `0` we instead have to inspect its output. Symfony Process will start any processes under Windows as a `cmd.exe` subprocess. As such `tasklist /FI "PID eq …"` will then have an output like this for the given process ID (with an English locale):

```
Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
cmd.exe                      15048 Console                    5      5
```

In case the PID is not found, the output will look like this:

```
INFO: No tasks are running which match the specified criteria.
```

Thus this PR assumes that as long as `cmd.exe` is in the output, the process with the given process ID is still actually running.

### CODE REVIEW

**Comment by Toflar** [comment]
I guess we should integrate this also into our tests and run those on windows only (and the current ones on linux only). I've just pushed the foundation for Github tests to `develop`. Can you rebase and maybe integrate the logic in the tests?

**Comment by fritzmg** [comment]
Hm, right now I can't come up with a way to adjust `countSleepProcesses()` for Windows though 🤔

**Comment by fritzmg** [comment]
I mean the test would work, if you run it in a cygwin or mingw command line under Windows - is that something you can set up? Then this could be merged as is.

**Comment by Toflar** [comment]
My goal would be to add another job in the workflows with `runs-on: windows-latest`. Does `tasklist` not contain all the `sleep` commands?

**Comment by fritzmg** [comment]
No, Symfony Process starts every process via `cmd.exe` - so `tasklist` will only see `cmd.exe` and nothing else (and you cannot inspect command arguments with `tasklist`).

**Comment by Toflar** [comment]
Maybe in conjunction with https://github.com/marketplace/actions/install-cygwin then? I'm not familiar with it at all so I don't think I can set this up^^

**Comment by fritzmg** [comment]
Besides, the `runner.php` will also only work on Unix and cygwin/mingw environments, as there is no `sleep` command under Windows.

**Comment by fritzmg** [comment]
> Maybe in conjunction with https://github.com/marketplace/actions/install-cygwin then? I'm not familiar with it at all so I don't think I can set this up^^

Me neither, but we can try ;)

**Pull request merged**
